// قائمة الولايات الجزائرية الـ 58 مرتبة حسب الرقم
export interface Wilaya {
  code: string;
  nameAr: string;
  nameFr: string;
}

export const WILAYAS: Wilaya[] = [
  { code: "01", nameAr: "أدرار", nameFr: "Adrar" },
  { code: "02", nameAr: "الشلف", nameFr: "Chlef" },
  { code: "03", nameAr: "الأغواط", nameFr: "Laghouat" },
  { code: "04", nameAr: "أم البواقي", nameFr: "Oum El Bouaghi" },
  { code: "05", nameAr: "باتنة", nameFr: "Batna" },
  { code: "06", nameAr: "بجاية", nameFr: "Béjaïa" },
  { code: "07", nameAr: "بسكرة", nameFr: "Biskra" },
  { code: "08", nameAr: "بشار", nameFr: "Béchar" },
  { code: "09", nameAr: "البليدة", nameFr: "Blida" },
  { code: "10", nameAr: "البويرة", nameFr: "Bouira" },
  { code: "11", nameAr: "تمنراست", nameFr: "Tamanrasset" },
  { code: "12", nameAr: "تبسة", nameFr: "Tébessa" },
  { code: "13", nameAr: "تلمسان", nameFr: "Tlemcen" },
  { code: "14", nameAr: "تيارت", nameFr: "Tiaret" },
  { code: "15", nameAr: "تيزي وزو", nameFr: "Tizi Ouzou" },
  { code: "16", nameAr: "الجزائر", nameFr: "Alger" },
  { code: "17", nameAr: "الجلفة", nameFr: "Djelfa" },
  { code: "18", nameAr: "جيجل", nameFr: "Jijel" },
  { code: "19", nameAr: "سطيف", nameFr: "Sétif" },
  { code: "20", nameAr: "سعيدة", nameFr: "Saïda" },
  { code: "21", nameAr: "سكيكدة", nameFr: "Skikda" },
  { code: "22", nameAr: "سيدي بلعباس", nameFr: "Sidi Bel Abbès" },
  { code: "23", nameAr: "عنابة", nameFr: "Annaba" },
  { code: "24", nameAr: "قالمة", nameFr: "Guelma" },
  { code: "25", nameAr: "قسنطينة", nameFr: "Constantine" },
  { code: "26", nameAr: "المدية", nameFr: "Médéa" },
  { code: "27", nameAr: "مستغانم", nameFr: "Mostaganem" },
  { code: "28", nameAr: "المسيلة", nameFr: "M'Sila" },
  { code: "29", nameAr: "معسكر", nameFr: "Mascara" },
  { code: "30", nameAr: "ورقلة", nameFr: "Ouargla" },
  { code: "31", nameAr: "وهران", nameFr: "Oran" },
  { code: "32", nameAr: "البيض", nameFr: "El Bayadh" },
  { code: "33", nameAr: "إليزي", nameFr: "Illizi" },
  { code: "34", nameAr: "برج بوعريريج", nameFr: "Bordj Bou Arréridj" },
  { code: "35", nameAr: "بومرداس", nameFr: "Boumerdès" },
  { code: "36", nameAr: "الطارف", nameFr: "El Tarf" },
  { code: "37", nameAr: "تندوف", nameFr: "Tindouf" },
  { code: "38", nameAr: "تيسمسيلت", nameFr: "Tissemsilt" },
  { code: "39", nameAr: "الوادي", nameFr: "El Oued" },
  { code: "40", nameAr: "خنشلة", nameFr: "Khenchela" },
  { code: "41", nameAr: "سوق أهراس", nameFr: "Souk Ahras" },
  { code: "42", nameAr: "تيبازة", nameFr: "Tipaza" },
  { code: "43", nameAr: "ميلة", nameFr: "Mila" },
  { code: "44", nameAr: "عين الدفلى", nameFr: "Aïn Defla" },
  { code: "45", nameAr: "النعامة", nameFr: "Naâma" },
  { code: "46", nameAr: "عين تموشنت", nameFr: "Aïn Témouchent" },
  { code: "47", nameAr: "غرداية", nameFr: "Ghardaïa" },
  { code: "48", nameAr: "غليزان", nameFr: "Relizane" },
  { code: "49", nameAr: "المغير", nameFr: "El M'Ghair" },
  { code: "50", nameAr: "المنيعة", nameFr: "El Meniaa" },
  { code: "51", nameAr: "أولاد جلال", nameFr: "Ouled Djellal" },
  { code: "52", nameAr: "برج باجي مختار", nameFr: "Bordj Baji Mokhtar" },
  { code: "53", nameAr: "بني عباس", nameFr: "Béni Abbès" },
  { code: "54", nameAr: "تيميمون", nameFr: "Timimoun" },
  { code: "55", nameAr: "تقرت", nameFr: "Touggourt" },
  { code: "56", nameAr: "جانت", nameFr: "Djanet" },
  { code: "57", nameAr: "عين صالح", nameFr: "In Salah" },
  { code: "58", nameAr: "عين قزام", nameFr: "In Guezzam" },
];
